# PATH
export PATH="/usr/local/bin:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/bin"

# make vim as default editor
export EDITOR=vim

# bashrc
if [ -f "$HOME/.bashrc" ] ; then
  source $HOME/.bashrc
fi

